name: windows95
version: '1.2.0'
summary: Windows 95, running in an Electron app.
description: |
  Windows 95, running in an Electron app.

  This is the windows95 electron app deb from
  https://github.com/felixrieseberg/windows95/releases
  re-packaged as a snap.

  You can find the source code for the snap at
  https://github.com/ogra1/windows95-snap

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  windows95:
    command: desktop-launch $SNAP/usr/bin/windows95
    plugs:
      - alsa
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11

parts:
  w95:
    after: [ desktop-gtk3 ]
    source: https://github.com/felixrieseberg/windows95/releases/download/v1.2.0/windows95-linux_1.2.0_amd64.deb
    plugin: nil
    override-build: |
      if [ "$SNAPCRAFT_ARCH_TRIPLET" != "x86_64-linux-gnu" ]; then
        exit 1
      fi
      cp -av usr $SNAPCRAFT_PART_INSTALL
    stage-packages:
      - libasound2
      - libnspr4
      - libnss3
      - libxss1
      - libxtst6
